name: membangun-model-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip:
      - xgboost==2.0.1
      - mlflow==2.8.1
      - dagshub==0.3.8
      - scikit-learn==1.3.2
      - pandas==2.1.3
