name: Train and Deploy Model to Docker Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write   

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
          lfs: true               

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: mlflow-env
          python-version: "3.10"
          channels: defaults,conda-forge
          auto-activate-base: false
          miniconda-version: "latest"

      - name: Initialize Conda
        shell: bash -l {0}
        run: |
          conda init bash
          conda info
          conda list
          which python
          python --version
          which pip
          echo "Active environment: $CONDA_DEFAULT_ENV"

      - name: Install MLflow
        shell: bash -l {0}
        run: |
          pip install mlflow
          pip show mlflow
          which mlflow

      - name: Verify Script Content
        shell: bash -l {0}
        run: cat MLproject/modelling_tunning.py

      - name: Set MLflow Tracking URI
        run: echo "MLFLOW_TRACKING_URI=file://$(pwd)/mlruns" >> $GITHUB_ENV

      - name: Run MLflow project
        id: train
        shell: bash -l {0}
        env:
          MLFLOW_DISABLE_ENV_MANAGER_CONDA_WARNING: "TRUE"
        run: |
          echo "--- Running mlflow run command with Conda environment manager ---"
          mlflow run MLproject/ --env-manager=conda -P dataset_path=personality_preprocessing/personality_preprocessing.csv

      - name: Setup Git LFS
        run: |
          git lfs install

      - name: Track MLflow artifacts with Git LFS
        run: |
          git lfs track "mlruns/**"
          git add .gitattributes

      - name: Commit MLflow artifacts to LFS
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update MLflow artifacts (mlruns) via Git LFS"
          file_pattern: |
            mlruns/**

      - name: Verify best_run_id.txt
        shell: bash -l {0}
        run: |
          ls -l MLproject/
          cat MLproject/best_run_id.txt

      - name: Get latest MLflow run_id
        shell: bash -l {0}
        run: |
          RUN_ID=$(cat MLproject/best_run_id.txt)
          echo "Best run ID: $RUN_ID"
          echo "RUN_ID=${RUN_ID}" >> $GITHUB_ENV

      - name: Build Docker Model
        shell: bash -l {0}
        run: |
          conda run -n mlflow-env --no-capture-output \
          mlflow models build-docker \
          --model-uri "runs:/${{ env.RUN_ID }}/model" \
          --name "personality-model"

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" \
            | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag personality-model:latest ${{ secrets.DOCKERHUB_USERNAME }}/personality-model:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/personality-model:latest
