name: Train and Deploy Model to Docker Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: mlflow-env
          python-version: "3.10"
          channels: defaults,conda-forge
          auto-activate-base: false
          miniconda-version: "latest"

      - name: Initialize Conda
        shell: bash -l {0}
        run: |
          conda init bash
          conda info
          conda list
          which python
          python --version
          which pip
          echo "Active environment: $CONDA_DEFAULT_ENV"

      - name: Install MLflow
        shell: bash -l {0}
        run: |
          pip install mlflow
          pip show mlflow
          which mlflow

      - name: Run MLflow project
        id: train
        shell: bash -l {0}
        run: |
          echo "--- Running mlflow run command with Conda environment manager ---"
          conda init bash
          mlflow run MLproject/ --env-manager=conda

      - name: Get latest MLflow run_id
        shell: bash -l {0}
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | awk -F '/' '{print $(NF-1)}')
          echo "RUN_ID=$RUN_ID"
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Build Docker Model
        shell: bash -l {0}
        run: |
            conda run -n mlflow-env --no-capture-output mlflow models build-docker --model-uri "runs:/$RUN_ID/best_model" --name "personality-model-docker"

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag personality-model-docker:latest ${{ secrets.DOCKERHUB_USERNAME }}/personality-model:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/personality-model:latest