name: Train and Deploy Model to Docker Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: mlflow-env
          python-version: "3.10"
          channels: defaults,conda-forge
          auto-activate-base: false
          miniconda-version: "latest"

      - name: Initialize Conda
        shell: bash -l {0}
        run: |
          conda init bash
          conda info
          conda list

      - name: Run MLflow Project
        working-directory: Membangun_model
        shell: bash -l {0}
        run: |
          echo "--- Running MLflow ---"
          mlflow run . --env-manager=conda -P dataset=personality_preprocessing/personality_preprocessing.csv

      - name: Get latest MLflow run_id
        id: get_run
        shell: bash -l {0}
        working-directory: Membangun_model
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Build Docker Model
        shell: bash -l {0}
        working-directory: Membangun_model
        run: |
          echo "--- Building Docker image from MLflow run ---"
          mlflow models build-docker --model-uri "runs:/${{ env.RUN_ID }}/best_model" --name "personality-model-docker"

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag personality-model-docker:latest ${{ secrets.DOCKERHUB_USERNAME }}/personality-model-docker:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/personality-model-docker:latest