name: Train and Deploy Model to Docker Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run MLflow project
        id: train
        run: |
          mlflow run MLproject --env-manager=local

      - name: Get latest MLflow run_id
        run: |
            RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
            echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
            echo "Latest run_id: $RUN_ID"

      - name: Install Docker CLI tools
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build Docker Image with MLflow
        run: |
          mlflow models build-docker \
            -m mlruns/${{ env.EXPERIMENT_ID }}/${{ env.RUN_ID }}/artifacts/best_model \
            -n personality-model

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag personality-model:latest ${{ secrets.DOCKERHUB_USERNAME }}/personality-model:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/personality-model:latest
